const jobData = [
  {
    title: "React.js Frontend Developer",
    hiringOrganizationName: "Tech Innovators Inc.",
    url: "https://example.com/reactjs-frontend-developer",
    region: "Remote",
    employmentType: "Freelance",
    published_since: "2024-09-01T00:00:00Z",
    websiteName: "TechJobsHub",
  },
  {
    title: "UX/UI Designer for Blockchain Startup",
    hiringOrganizationName: "Blockchain Creatives",
    url: "https://example.com/ux-ui-designer-blockchain",
    region: "Remote",
    employmentType: "Freelance",
    published_since: "2024-08-25T00:00:00Z",
    websiteName: "DesignJobs",
  },
  {
    title: "Senior Full Stack Developer with Blockchain Experience",
    hiringOrganizationName: "Web3 Solutions",
    url: "https://example.com/full-stack-blockchain-developer",
    region: "Remote",
    employmentType: "Freelance",
    published_since: "2024-08-20T00:00:00Z",
    websiteName: "BlockchainJobs",
  },
  {
    title: "React.js Developer for E-Commerce Platform",
    hiringOrganizationName: "E-Com Experts",
    url: "https://example.com/reactjs-ecommerce-developer",
    region: "Remote",
    employmentType: "Freelance",
    published_since: "2024-08-15T00:00:00Z",
    websiteName: "TechJobsHub",
  },
  {
    title: "Freelance Blockchain Developer",
    hiringOrganizationName: "Crypto Ventures",
    url: "https://example.com/freelance-blockchain-developer",
    region: "Remote",
    employmentType: "Freelance",
    published_since: "2024-08-10T00:00:00Z",
    websiteName: "BlockchainJobs",
  },
  {
    title: "UI/UX Designer for Mobile App",
    hiringOrganizationName: "App Design Studio",
    url: "https://example.com/ui-ux-designer-mobile-app",
    region: "Remote",
    employmentType: "Freelance",
    published_since: "2024-08-05T00:00:00Z",
    websiteName: "DesignJobs",
  },
  {
    title: "Freelance React.js Developer for Startup",
    hiringOrganizationName: "Innovative Tech",
    url: "https://example.com/freelance-reactjs-developer",
    region: "Remote",
    employmentType: "Freelance",
    published_since: "2024-07-30T00:00:00Z",
    websiteName: "TechJobsHub",
  },
  {
    title: "Blockchain Developer for Decentralized App",
    hiringOrganizationName: "FutureTech Labs",
    url: "https://example.com/blockchain-developer-dapp",
    region: "Remote",
    employmentType: "Freelance",
    published_since: "2024-07-25T00:00:00Z",
    websiteName: "BlockchainJobs",
  },
  {
    title: "UI/UX Designer for Web Platform",
    hiringOrganizationName: "Creative Minds",
    url: "https://example.com/ui-ux-designer-web-platform",
    region: "Remote",
    employmentType: "Freelance",
    published_since: "2024-07-20T00:00:00Z",
    websiteName: "DesignJobs",
  },
  {
    title: "React.js Developer for Social Media App",
    hiringOrganizationName: "SocialTech Co.",
    url: "https://example.com/reactjs-social-media-app",
    region: "Remote",
    employmentType: "Freelance",
    published_since: "2024-07-15T00:00:00Z",
    websiteName: "TechJobsHub",
  },
  {
    title: "Freelance Blockchain Architect",
    hiringOrganizationName: "Blockchain Visionaries",
    url: "https://example.com/freelance-blockchain-architect",
    region: "Remote",
    employmentType: "Freelance",
    published_since: "2024-07-10T00:00:00Z",
    websiteName: "BlockchainJobs",
  },
  {
    title: "React.js and Node.js Developer",
    hiringOrganizationName: "FullStack Innovations",
    url: "https://example.com/reactjs-nodejs-developer",
    region: "Remote",
    employmentType: "Freelance",
    published_since: "2024-07-05T00:00:00Z",
    websiteName: "TechJobsHub",
  },
  {
    title: "Freelance UI/UX Designer for SaaS Platform",
    hiringOrganizationName: "SaaS Design Experts",
    url: "https://example.com/ui-ux-designer-saas",
    region: "Remote",
    employmentType: "Freelance",
    published_since: "2024-06-30T00:00:00Z",
    websiteName: "DesignJobs",
  },
  {
    title: "Blockchain Smart Contract Developer",
    hiringOrganizationName: "SmartContract Pros",
    url: "https://example.com/blockchain-smart-contract-developer",
    region: "Remote",
    employmentType: "Freelance",
    published_since: "2024-06-25T00:00:00Z",
    websiteName: "BlockchainJobs",
  },
  {
    title: "React.js Developer for Healthcare App",
    hiringOrganizationName: "HealthTech Solutions",
    url: "https://example.com/reactjs-healthcare-app",
    region: "Remote",
    employmentType: "Freelance",
    published_since: "2024-06-20T00:00:00Z",
    websiteName: "TechJobsHub",
  },
  {
    title: "Freelance UX/UI Designer for FinTech Startup",
    hiringOrganizationName: "FinTech Designers",
    url: "https://example.com/ux-ui-designer-fintech",
    region: "Remote",
    employmentType: "Freelance",
    published_since: "2024-06-15T00:00:00Z",
    websiteName: "DesignJobs",
  },
  {
    title: "React.js Developer for Educational Platform",
    hiringOrganizationName: "EduTech Innovators",
    url: "https://example.com/reactjs-educational-platform",
    region: "Remote",
    employmentType: "Freelance",
    published_since: "2024-06-10T00:00:00Z",
    websiteName: "TechJobsHub",
  },
  {
    title: "Freelance Blockchain Consultant",
    hiringOrganizationName: "Blockchain Experts",
    url: "https://example.com/freelance-blockchain-consultant",
    region: "Remote",
    employmentType: "Freelance",
    published_since: "2024-06-05T00:00:00Z",
    websiteName: "BlockchainJobs",
  },
  {
    title: "UI/UX Designer for SaaS Product",
    hiringOrganizationName: "SaaS Vision",
    url: "https://example.com/ui-ux-designer-saas-product",
    region: "Remote",
    employmentType: "Freelance",
    published_since: "2024-05-30T00:00:00Z",
    websiteName: "DesignJobs",
  },
  {
    title: "Freelance React.js Developer for Mobile App",
    hiringOrganizationName: "MobileTech Solutions",
    url: "https://example.com/reactjs-mobile-app",
    region: "Remote",
    employmentType: "Freelance",
    published_since: "2024-05-25T00:00:00Z",
    websiteName: "TechJobsHub",
  },
  {
    title: "Blockchain Developer for NFT Marketplace",
    hiringOrganizationName: "NFT Creators",
    url: "https://example.com/blockchain-developer-nft",
    region: "Remote",
    employmentType: "Freelance",
    published_since: "2024-05-20T00:00:00Z",
    websiteName: "BlockchainJobs",
  },
  {
    title: "Freelance UI/UX Designer for Tech Startup",
    hiringOrganizationName: "Tech Startup Designers",
    url: "https://example.com/ui-ux-designer-tech-startup",
    region: "Remote",
    employmentType: "Freelance",
    published_since: "2024-05-15T00:00:00Z",
    websiteName: "DesignJobs",
  },
  {
    title: "React.js Developer for E-Learning Platform",
    hiringOrganizationName: "E-Learning Innovators",
    url: "https://example.com/reactjs-elearning-platform",
    region: "Remote",
    employmentType: "Freelance",
    published_since: "2024-05-10T00:00:00Z",
    websiteName: "TechJobsHub",
  },
  {
    title: "Freelance Blockchain Integration Developer",
    hiringOrganizationName: "Integration Experts",
    url: "https://example.com/blockchain-integration-developer",
    region: "Remote",
    employmentType: "Freelance",
    published_since: "2024-05-05T00:00:00Z",
    websiteName: "BlockchainJobs",
  },
];

export default jobData;
``;
